---
development:
  cloud_name: hu986w9zs
  api_key: '859531535148367'
  api_secret: O_H4w96hp9EsnZo1J4d_QE2ip
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hu986w9zs
  api_key: '859531535148367'
  api_secret: O_H4w96hp9EsnZo1J4d_QE2ip
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hu986w9zs
  api_key: '859531535148367'
  api_secret: O_H4w96hp9EsnZo1J4d_QE2ip
  enhance_image_tag: true
  static_image_support: false
